name: test-windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Test Compile ${{ matrix.config }} ${{ matrix.arch }}
    runs-on: windows-latest
    env:
      CC: cl.exe
      CXX: cl.exe

    strategy:
      matrix:
        config: [Release, Debug]
        arch: [Win32, x64]

    steps:
      - uses: actions/checkout@v2.1.1

      - uses: ilammy/msvc-dev-cmd@v1.2.0

      - name: Configure build
        shell: cmd
        run: cmake -Bbuild -A ${{ matrix.arch }} -DWARNINGS_AS_ERRORS=ON .

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ matrix.config }}

      - name: binding-functions
        working-directory: build
        run: |
          cmake --build . --config ${{ matrix.config }} --target binding-functions
          if ((Get-Item "binding-functions").Length -lt 10) { $host.SetShouldExit(1) }

      # TODO: Doesn't work because of tests reading from stdin
      # - name: Tests
      #   working-directory: build
      #   shell: cmd
      #   env:
      #     CTEST_OUTPUT_ON_FAILURE: 1
      #   run: ctest -C ${{ matrix.config }}
